name: XPadel API Deplyo
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DIGITAL_OCEAN_DROPLET_IP}}
          username: ${{secrets.DIGITAL_OCEAN_DROPLET_USERNAME}}
          key: ${{secrets.DIGITAL_OCEAN_DROPLET_KEY}}
          script: >
            cd xpadel &&
            DATABASE_URL="${{secrets.DATABASE_URL}}" 
            APP_SECRET=${{secrets.APP_SECRET}} 
            SERVER_NAME=${{secrets.SERVER_NAME}}
            docker compose -f compose.yaml -f compose.prod.yaml up -d
             
