# Development environment override
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: frankenphp_dev
    volumes:
      - ./backend:/app
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./docker/php/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
    environment:
      PHP_IDE_CONFIG: "serverName=xpadel"
      XDEBUG_SESSION: 1
      XDEBUG_MODE: "${XDEBUG_MODE:-debug}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      target: dev
    volumes:
      - ./frontend:/home/node/app

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: xpadel
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "xpadel", "-U", "postgres" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  database_data: