services:
  php:
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-http://localhost}, php:80
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - "80:80"
      # HTTPS
      - "443:443"

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: xpadel
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "xpadel", "-U", "postgres"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  caddy_data:
  caddy_config:
  database_data:
