services:
  php:
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-http://localhost}, php:80
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:password@database:5432/xpadel?serverVersion=16&charset=utf8}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - "80:80"
      # HTTPS
      - "443:443"
      # HTTP/3
      - "443:443/udp"

volumes:
  caddy_data:
  caddy_config:
