# Production environment override
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: frankenphp_prod
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_SECRET: ${APP_SECRET}
      AWS_S3_ACCESS_ID: ${AWS_S3_ACCESS_ID}
      AWS_S3_ACCESS_SECRET: ${AWS_S3_ACCESS_SECRET}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      target: prod
    environment:
      API_URL: ${API_URL}
      AUTH_SECRET: ${AUTH_SECRET}