# Production environment override
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: frankenphp_prod
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_SECRET: ${APP_SECRET}

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      target: prod
    environment:
      API_URL: ${API_URL}
      AUTH_SECRET: ${AUTH_SECRET}