services:
  php:
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-:80}, php:80
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - "80:80"
      # HTTPS
      - "443:443"
      # HTTP/3
      - "443:443/udp"

  node:
    restart: unless-stopped
    expose:
      - "3000"

volumes:
  caddy_data:
  caddy_config:
