services:
  database:
    image: postgres:16
    container_name: xpadel_database
    restart: always
    environment:
      POSTGRES_DB: xpadel_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: