name: XPadel Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/**
      - frontend/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup production ssh configuration
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: ${{secrets.SERVER_IP}}
          private-key: ${{ secrets.SERVER_KEY }}
      - name: Deploy
        run: |
          ssh ${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_IP}} << 'EOF'
            cd xpadel
            git fetch
            git reset --hard origin/main
          
            AWS_S3_ACCESS_ID=${{secrets.AWS_S3_ACCESS_ID}} \
            AWS_S3_ACCESS_SECRET=${{secrets.AWS_S3_ACCESS_SECRET}} \
            AWS_S3_BUCKET=${{secrets.AWS_S3_BUCKET}} \
            DATABASE_URL="${{secrets.DATABASE_URL}}" \
            APP_SECRET="${{secrets.APP_SECRET}}" \
            AUTH_SECRET="${{secrets.AUTH_SECRET}}" \
            SERVER_NAME="xpadel.app" \
            API_URL="https://xpadel.app/api" \
            docker compose -f compose.yaml -f compose.prod.yaml up -d --build
          
            docker compose exec php frankenphp reload --config /etc/caddy/Caddyfile
          EOF
