name: XPadel API Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{secrets.SERVER_KEY}}
          script: >
            cd xpadel &&
            git fetch &&
            git reset --hard origin/main &&
            DATABASE_URL="${{secrets.DATABASE_URL}}" 
            APP_SECRET=${{secrets.APP_SECRET}} 
            SERVER_NAME=${{secrets.SERVER_NAME}}
            docker compose -f compose.yaml -f compose.prod.yaml up -d
             
